services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/ -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
